### ISSUE TITLE
Add git installation instructions for OSX users in the documentation

### ISSUE THREAD

**Issue by mansimarkaur** [anitab-org/portal#203]
The instruction to install `git` for OSX users is missing from the `Setup the Project` section in the documentation.

**Comment by tonythomas01** [comment]
I personally think we should not document OS specific information for git/dependencies that are not directly related to the project.

**Comment by tapasweni-pathak** [comment]
We can ask for blog posts or wiki pages from GCI participants how they installed Portal on their machine.

**Comment by sonakshisaxena1** [comment]
Hello @tapasweni-pathak 
I would like to work on this issue. Am I only supposed to figure out the way in which OSX users install git or the blog post/wiki page is required?

**Comment by monajalal** [comment]
Actually, we have been thinking of having supports for main OS distros that are OSX, Windows 10, Ubuntu, and CentOS7. Some of these commands won't work in any platform!
Additionally, if the Docker is made for Ubuntu, sometimes it needs tweaking to get it work in CentOS (based on prior experience).

**Comment by sakshi1499** [comment]
I don't think we should add it in setup. Closing it.
