### ISSUE TITLE
Error in downloading an image while running portal in a docker container

### ISSUE THREAD

**Issue by sonakshisaxena1** [anitab-org/portal#217]
After following the mentioned steps in the **Run Portal in a Docker Container** correctly when I tried the following code: 

`docker run -e SECRET_KEY=foobarbaz portal_web`
 
I received an error-

`Unable to find image 'portal_web:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout.
See 'docker run --help'.`

 
![screen shot 2017-10-02 at 2 03 49 am](https://user-images.githubusercontent.com/24795489/31058732-05ca71a4-a716-11e7-942e-3840de4acd63.png)

**Comment by tapasweni-pathak** [comment]
Can you please also share ```docker version```, ```docker info```, ```uname -a``` and ```docker inages```?

**Comment by sonakshisaxena1** [comment]
-boot2docker: Version 1.3.0
-docker: Version 17.06.2-ce-mac27, build cec0b72
-uname: Darwin Sonas-MacBook-Air.local 17.0.0 Darwin Kernel Version 17.0.0

The above screenshot is on boot2docker used in as terminal with Docker running in the background. Should I post any other screenshots?

**Comment by tonythomas01** [comment]
It seems like a tls handshake timeout. Are you behind a proxy (firewall) ? https://github.com/docker/kitematic/issues/1125 or https://stackoverflow.com/questions/34262275/docker-tls-handshake-timeout 

If yes, try from another network and please paste the out.

**Comment by sonakshisaxena1** [comment]
Yes, I was behind a proxy. I even tried to change it but was unable to figure it out. (I work in MacOS). Anyways, I’ll try to do it in some other network and will share it with you as soon as possible.
Thankyou :)

**Comment by sonakshisaxena1** [comment]
@tonythomas01 I tried using another network but it shows the same error. Can you please suggest me how change the proxy of MacOS?

**Comment by tonythomas01** [comment]
> @tonythomas01 I tried using another network but it shows the same error. Can you please suggest me how change the proxy of MacOS? 

To confirm, can you make sure: 
```
➜  ~ wget https://registry-1.docker.io/v2/
--2017-10-04 16:39:26--  https://registry-1.docker.io/v2/
Resolving registry-1.docker.io (registry-1.docker.io)... 54.152.220.218, 52.206.156.207, 54.85.174.159, ...
Connecting to registry-1.docker.io (registry-1.docker.io)|54.152.220.218|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
➜  ~ 
``` 
happens ?

**Comment by sonakshisaxena1** [comment]
Yes. It happens.
![screen shot 2017-10-04 at 8 27 50 pm](https://user-images.githubusercontent.com/24795489/31182829-8fef2112-a942-11e7-8fda-5b7e1c90c041.png)

**Comment by tonythomas01** [comment]
hmm. Looks like not a TLS issue then :-(

**Comment by sonakshisaxena1** [comment]
What should I do then?
If I don't get this running, I won't be able to contribute anymore :-(

**Comment by tonythomas01** [comment]
This should not block you - go for https://github.com/systers/portal#setup-for-developers -- and continue without deploying the portal on top of a docker. Someone will figure something out in the meanwhile.

**Comment by sonakshisaxena1** [comment]
Okay, thanks.

**Comment by mayburgos** [comment]
No one is currently using Docker to run Portal. We're going to update our documentation so we don't have Docker setup instructions.
