### ISSUE TITLE
REST API for Portal meetup data to be accessed internally for vola

### ISSUE THREAD

**Issue by tapaswenipathak** [anitab-org/portal#263]
Plan is to expose Portal meetup data within Systers project; currently to vola with auth.
Portal meetup does not track all given [here](https://github.com/systers/volunteers-android/blob/develop/docs/Schema.pdf) -> `starred events`.

As discussed ticketing it out; please let me know if there are any other specific requirements, here.

Requested:
>  - if the api has filters. ex. Getting events in a city. ( filtering by location ) etc
> - Possible fields in [Schema](https://github.com/systers/volunteers-android/blob/develop/docs/Schema.pdf)
> - Docs

cc/ @HimanshiJain, @pandilladivya, @mansimarkaur, @sa7i, @MeepyMay.

**Comment by arunikayadav42** [comment]
Can I start working on this issue?

**Comment by sakshee-19** [comment]
@tapasweni-pathak  I would like to work on this.

**Comment by ShubhamBansal1997** [comment]
@tapasweni-pathak @sakshee-19 @arunikayadav42 Anyone working on this issue. If not then I would like to work on this.

**Comment by satya7289** [comment]
@tapaswenipathak @isabelcosta  I want to work on this issue.

**Comment by mayburgos** [comment]
Volunteers App was archived and no longer in production.
