### ISSUE TITLE
Searching a meetup location

### ISSUE THREAD

**Issue by poojithansl** [anitab-org/portal#265]
Currently, 20 meetup locations are possible on the meetup/location page. If there are more than 20, it would be difficult to go through all pages to find the required meetup location, there must either be a search feature or limiting it to 20(pagination) must be removed. 
![image](https://user-images.githubusercontent.com/13400691/33337120-fa6bdda2-d497-11e7-9dd6-843d3c63bf16.png)
Searching a meetup location can be improved by modifying the map marker. Clicking the marker on the map must redirect us to the meetup location page, instead of the location name.
![image](https://user-images.githubusercontent.com/13400691/33337782-18ed29a0-d49a-11e7-9141-a254db66fb4d.png)

**Comment by tapasweni-pathak** [comment]
This looks 💯 to me.

**Comment by Vishnupriya1507** [comment]
Hi , can i take up this issue.

**Comment by sakshi1499** [comment]
@Vishnupriya1507 Do you want to work on it? Given that it has been really long since you commented.

**Comment by saurabhkanswal** [comment]
@sakshi1499  i think we should close this issue and create a new issue with remaining work i.e for

- Implement text search for meetup locations.

**Comment by sakshi1499** [comment]
@saurabhkanswal We have actually changed the whole idea of meetups now, so yes we should close it. Closing this issue.
