### ISSUE TITLE
Share buttons on a meetup event and a notify using google calendar button

### ISSUE THREAD

**Issue by poojithansl** [anitab-org/portal#268]
Every meetup event can be shared using the following buttons
- Facebook
- Twitter
- Google plus
- Linkedin
Add a google calendar notify button, Purpose of it being the event would be added to the google calendar of the user.

**Comment by tapasweni-pathak** [comment]
Closed w/ 57325ea07e063bdd319bac89d922ff7b244db527.

**Comment by saurabhkanswal** [comment]
@anitab-org/portal-managers  there is a some work left in this issue i.e
**Add a google calendar notify button, Purpose of it being the event would be added to the google calendar of the user.**
did we need this or we put this as future feature?

**Comment by sakshi1499** [comment]
We don't need this, google calendar feature can be in a separate PR.
