### ISSUE TITLE
Adding Twitter feeds to Communities and Meetups

### ISSUE THREAD

**Issue by poojithansl** [anitab-org/portal#269]
Create a Media section in Communities and add a twitter feed to it. 
Add twitter feed to every Meetup location.
Add twitter feed to the Meetups Main page.

**Comment by anjali-dhanuka** [comment]
Hey @sa7i, are you asking to create  a separate section for twitter feeds of organisations?

**Comment by tapasweni-pathak** [comment]
@anjali-dhanuka A bit late to tag, the issues raised by @sa7i are her ongoing Outreachy work. Please feel free to pick other issues, create new and contribute. 🎉

**Comment by sakshi1499** [comment]
Closing this issue as the PR for this issue has been merged already.
