### ISSUE TITLE
Authorization Levels on the Portal Application

### ISSUE THREAD

**Issue by poojithansl** [anitab-org/portal#272]
Super Users | Community Leaders | Community Moderators | Users 
-- | --|--|--
| Overrides the following in Meetups & Community: Activities, Content, Roles/Memberships (Assign/Remove/Revoke Community Leaders) | Manages all of the following in assigned Meetups & Community: Activities, Content, & Roles/Memberships | Approve/Reject Membership: Approve/Disapprove Community & Meetup Location Join Requests | Signup/Login Required: Facebook, Google, GitHub, Twitter |
| Create/Edit/Delete Communities & Meetup Locations (Cities) | **Activities:** Create/Edit Meetup Events (Request for Meetup Event Support with 3 Week Advance Notice -- catering, venue, promotional/marketing items), Request to Delete/Cancel a Meetup Event | Approve new Community Content Suggestions: Approve/Add/Edit/Delete tags, resource types, community news, community resources | Join a Community or Join a Meetup Location (City) |
| Notified about new Meetup Location (City) Requests | **Content:** Community Profile/Resources/Description, Meetup Location Profile/Event Details, Community & Meetup Location Members (Information & Profile Details) | Approve the first post of a member. | RSVP to a Meetup Event. | 
| Approve/Reject new Meetup Event Request (Approve/Reject Meetup Event Support Requests) | **Roles/Memberships:** Assign/Remove/Revoke Community Moderators | Able to delete comments in both Meetup/Community: Moderate the comments | Add Post/Comment in both Meetup/Community (1st post needs approval) |
|+ All of the Community Leaders Permissions | + All of the Community Moderators Permissions | + All of the Users Permissions | Add tags, resource types, community news, community resources |
| | | | Report a Post/Comment (Spam or Violations of Code of Conduct) -- Moderators get notified. |
| | | | Request a Meetup Event (Needs Community Managers’ or Super Users’ approval before added to the map) |
| | | | Request a Community (both Affinity & Meetup Location (City)) through Application. (Approved by Super User) |

### Notes: 
+ Usually more than 1 Community Leader is assigned to a Community or Meetup Location.
  + Example: Latinas in Computing has 3 leaders,
+ After the first post is approved, no approval needed for additional posts.

### Enhancements:
+ Attaching an image/media.
+ Post in Community Resources “discussion threads”
+ Reported Posts/Comments
  + Moderators & Community Managers get notified. 
  + If post/comment does not get resolved within 48 hours, Super Users get notified.

Things to do:
- The user must be able to request a meetup location, and admin able to approve it.
- The user must be able to request a meetup event and admin/organizer able to approve it.
- Create a Sponsor Us Page and FAQ Page to every meetup location.
- Add meetup locations must be on the main meetup page.
- Admin must be able to create a new community.
- Implement a search feature for meetup locations.
- Implement Twitter feeds on meetup location pages
- Upcoming meetups on main meetup location page.
- Migrate portal regularly.
- Share buttons on a meetup event page.
- Photos of every meetup event on meetup location page.(Low priority)
- Discussion area on each meetup location. (Low priority)

Some Enhancements proposed over gsoc16 work:
- Reporting a comment on a meetup.
- Admin/Organiser able to delete the comment.

(More can be added to this, once all the gsoc work gets merged).

Discussion point:
- Do communities need media section in which twitter feeds are included?
- It'd be useful for users to have an 'add to google calendar' button like [this](https://community.anitab.org/event/cameroon-planning-meeting/) that can act as a reminder, instead of sending out mails.

**Comment by tapasweni-pathak** [comment]
👋 @sa7i, are you writing about what we plan to do?

**Comment by sa7i** [comment]
Forgot about that. I will do it today. :)
