### ISSUE TITLE
Add check on "no of volunteers" field in New community proposal form 

### ISSUE THREAD

**Issue by anjali-dhanuka** [anitab-org/portal#277]
## Description
Negative integers in no of volunteers field in new community proposal form must not be saved.
Error message must be displayed for that.

![screenshot from 2017-12-06 16-36-18](https://user-images.githubusercontent.com/22369767/33676347-877e164e-dadb-11e7-9bf4-31fd48e03fce.png)

**Comment by arunikayadav42** [comment]
If nobody else is then I am getting started on this issue

**Comment by sa7i** [comment]
Hi @arunikayadav42, the community proposal form is a Google doc, so there won't be anything from our side to work on this.

**Comment by tapasweni-pathak** [comment]
@sa7i We would be going ahead w/ a form instead so that admin can say approve and then enable the addition of new community. Having a Google Document and having a separate form only for admin doesn't sound good in terms of usability.

**Comment by sa7i** [comment]
@tapasweni-pathak , In that case, I don't think we'd need the add community by admin form or do you think it'd be better to have that one as well?

**Comment by tapasweni-pathak** [comment]
There should be one form, admin should be able to approve and edit the details. Once they approve it published as a community.

**Comment by sakshi1499** [comment]
Don't need this issue. Closing it.
