### ISSUE TITLE
Check all migration file and see if they can be improved

### ISSUE THREAD

**Issue by tapaswenipathak** [anitab-org/portal#278]
- renaming.
- why are they squashed if they are.

@sa7i Please write your observation in this issue.

**Comment by arunikayadav42** [comment]
Can I please work on this issue?

**Comment by sa7i** [comment]
Hi @arunikayadav42, all the issues that are tagged [Program: Outreachy Ongoing](https://github.com/systers/portal/labels/Program%3A%20Outreachy%20Ongoing) are assigned to me to work on as part of my outreachy internship. Please feel free to pick other issues, create new and contribute. :dancer:

**Comment by saurabhkanswal** [comment]
closing as this issue is not relevant.
