### ISSUE TITLE
Poojitha Nandigam Outreachy Round'15

### ISSUE THREAD

**Issue by tapaswenipathak** [anitab-org/portal#287]
👋 Poojitha, keep this as the list of todos for your Outreachy internship and tick the checkboxes as you complete them. Few of these would only be completed when you complete your internship.

- [x] Publish your timeline, blog link on Portal wiki. [Ref](https://github.com/systers/vms/wiki/GSOC-16--Work-:-AUT-VMS-%5Bvatsala%5D).
- [x] Open broad issues for your Outreachy work including how you would be resolving them discussed w/ @tapasweni-pathak and list them down w/ checkboxes, as a comment on this issue.
- [ ] Go through existing issue queue and tag @tapasweni-pathak if you think they should not be open now w/ your observations.
- [x] Answer questions on Slack for people who are getting started with contributing to Systers Portal.
- [x] Assign priority to tasks w/ @tapasweni-pathak and @MeepyMay.
- [ ] Send email of your blog bi weekly to your mentors @mansimarkaur, @tapasweni-pathak.
- [ ] Raise 5 more issues/bugs/enhancements not part of your work timeline.
- [ ] Sync/Demo w/ @rosariorobinson as planned by @MeepyMay.
- [ ] You may get few adhoc tasks assigned to you during your internship time period raised by @tapasweni-pathak, feel free to discuss what you want to take up, what you don't.

If you have any questions shoot an email, or a tag me on GitHub. I may take some time but I'll get back as soon as I can. Let me know if you get stuck w/ something for long, happy to look into it w/ you. 🚀

**Comment by sa7i** [comment]
- [x]  Publish your timeline, blog link on Portal wiki. [Ref.](https://github.com/systers/vms/wiki/GSOC-16--Work-:-AUT-VMS-%5Bvatsala%5D)
- [x] Open broad issues for your Outreachy work including how you would be resolving them discussed w/ @tapasweni-pathak and list them down w/ checkboxes, as a comment on this issue.
- [x] Answer questions on Slack for people who are getting started with contributing to Systers Portal.
- [x]  Assign priority to tasks w/ @tapasweni-pathak and @MeepyMay.

**Comment by saurabhkanswal** [comment]
closing this issue as it is not relevant now.
