### ISSUE TITLE
Log in with Google account shows Oauth error

### ISSUE THREAD

**Issue by kriti21** [anitab-org/portal#299]
## Mocks
![portal6](https://user-images.githubusercontent.com/19872082/34939965-d185c348-fa13-11e7-93b3-9d0703c1ba69.png)

**Comment by imrshu** [comment]
@kriti21 It seems like Systers Portal's Oauth Client & Secret has been changed or deleted in Google developers console

**Comment by Vishnupriya1507** [comment]
Hi, can i take this issue.

**Comment by satya7289** [comment]
duplicate of issue 533
