### ISSUE TITLE
Updating the RSVP of a meetup second time throws an error.

### ISSUE THREAD

**Issue by poojithansl** [anitab-org/portal#311]
Steps to reproduce this
RSVP to a meetup. 
RSVP to the same meetup again.
Error Thrown 
![image](https://user-images.githubusercontent.com/13400691/36368849-254df9ec-157f-11e8-8be5-a042b71738b6.png)

**Comment by sammy1997** [comment]
@sa7i @Janiceilene @prachi1210 Can I please work on this? Please verify that this is a correct error?

**Comment by sa7i** [comment]
Please go ahead.

**Comment by sammy1997** [comment]
@sa7i When I created a meetup for an event, /rsvp gives errors. I am an organiser for this event. I am getting access denied page. Is this a correct way to go?

**Comment by sa7i** [comment]
No, that's not how it should work. As you stated in the other issue, it's a bug.

**Comment by sammy1997** [comment]
So how can I generate this RSVP error if this error isn't solved

**Comment by sa7i** [comment]
@sammy1997 Two ways- you can accept the join requests by being a super user. Accept them. This way you can work on it without changing code . The other way is to add these lines https://github.com/systers/portal/pull/328/commits/1d23dc876ac5876ba1032e01cf3334bb6ea84e2f

**Comment by sammy1997** [comment]
@sa7i I have some problems with this issue. Can you see the discussions on Slack ?

**Comment by monajalal** [comment]
@sa7i can you please edit this issue so that it follows the pattern of other issues and clearly states the number of mentors who should review it as well as the guideline to accept the changes? Thanks

**Comment by sammy1997** [comment]
Making this issue available to students. Have closed the linked PR.

**Comment by ritwickraj78** [comment]
@sammy1997  I would like to work on this issue. May I proceed?

**Comment by sammy1997** [comment]
Yeah go ahead
