### ISSUE TITLE
Members/Organizers of a Meetup Location should have the flexibility to change the extent of their involvement in that meetup

### ISSUE THREAD

**Issue by Nik-Khandelwal** [anitab-org/portal#317]
## Description
As a Member of a meetup,
I need to have a Leave Meetup Location Button,
so that I can have the flexibility of leaving the meetup location if necessary.

Similarly as a Organiser of a meetup,
I need to have a Leave as Organiser and a Leave Meetup Location Button,
so that I can contribute to the meetup according to my convenience.

I can work on this.

### Update [Required]
- [ ] A Leave Meetup Location Button for members of a meetup.
- [ ] Leave as Organizer and Leave Meetup Location Button for organisers of a meetup
- [ ] The buttons must conform to the general UI of the meetup section of the portal

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by sakshi1499** [comment]
Not required anymore.
