### ISSUE TITLE
Membership must also include Meetup Locations. 

### ISSUE THREAD

**Issue by poojithansl** [anitab-org/portal#332]
## Description
Membership of a user can be shown next to the user's profile. Currently, membership only includes the community membership. But, Meetup membership must also be included. 
e.g. If I am a Community Member of Systers and Meetup location member of London Systers. Membership only shows that I am part of Systers.

## Mocks
![image](https://user-images.githubusercontent.com/13400691/36833434-5703b674-1d55-11e8-96e8-6822510893c4.png)

## Acceptance Criteria
Include Meetup Location membership and provide options to leave, leave as an organizer.
### Update [Required]
- [ ] Meet the acceptance criteria.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1/2 hours

**Comment by imrshu** [comment]
@sa7i I will you a PR for this issue.

**Comment by sammy1997** [comment]
@imrshu R u still working on this?

**Comment by Praful932** [comment]
@sammy1997 I would like to work on this issue

**Comment by sammy1997** [comment]
Go ahead @Praful932

**Comment by Praful932** [comment]
@sammy1997 I had trouble with rebase in the first PR. I have made a new PR #522 , Please Check Thank you.

**Comment by sakshi1499** [comment]
This issue is irrelevant now. Pr for this has been already closed.
