### ISSUE TITLE
Bug - Date is empty in Join requests for meetup location.

### ISSUE THREAD

**Issue by poojithansl** [anitab-org/portal#334]
## Description
Date is empty in every join requests for meetup location as seen in the image
## Mocks
![image](https://user-images.githubusercontent.com/13400691/36835068-f967c1f8-1d5a-11e8-975d-848059d90144.png)

## Acceptance Criteria
Join requests for a meetup location doesn't contain any date field. So, for every join request the date shows empty. Remove date. 

### Update [Required]
- [ ] Meet the Acceptance Criteria.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour
First timer task

**Comment by SETIADEEPANSHU** [comment]
Can I take this issue !

**Comment by abhi20161997** [comment]
I'll be working on it.

**Comment by SETIADEEPANSHU** [comment]
I have already done it ! I am just working on PR template, hope you don't mind!

**Comment by abhi20161997** [comment]
@SETIADEEPANSHU  it's completely fine with you doing this but please abide by the code of conduct in future cause I'd mentioned I'd be working on that :)

**Comment by SETIADEEPANSHU** [comment]
@abhi20161997 I think you are mistaken , @sa7i asked me to solve it , may be she might have mistakenly asked you also. Not my fault!

**Comment by satya7289** [comment]
As we are going to remove the meetup location feature, so this issue will become irreverent. So we are closing the issue.
