### ISSUE TITLE
Dev file should be ignored.

### ISSUE THREAD

**Issue by yashLadha** [anitab-org/portal#342]
## Description
As a new contributor, i need to setup the project for the contribution, but i need to set the database preferences in the dev file, and they started watching from the git, contributor mistakenly push the file and merged from a list of changes might lead to confusion or build failure in later future.

## Mocks
N/A

## Acceptance Criteria
* Code is not changed

## Definition of Done
- [x] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by sa7i** [comment]
@yashLadha  I don't see this as an issue to work on. The solution proposed in the PR only makes the code unnecessarily complicated. Carefully doing `git add` could solve this.

**Comment by aviaryan** [comment]
I feel both ways on this problem. Sure, having a separate `*.py` file for development helps but it also adds unnecessary steps to the "getting started" process. 
So I think we should leave it as it is.
Do you have any real-life examples that can help strengthen your proposal?

**Comment by yashLadha** [comment]
If someone working on a lengthy process and changed in the dev setting for
DB connection and them the PR is pushed. It would be easy to just copy a
single file in installation instruction them to constantly ignore the file
while staging files for commit.

**Comment by sakshi1499** [comment]
Closing this, I don't think its required at the moment.
