### ISSUE TITLE
Custom Admin Functionality

### ISSUE THREAD

**Issue by AnkurBegining** [anitab-org/portal#347]
## Description
As a admin, I should be able to search and filter in admin page and use  the custom functionality for enhancing admin page. By default, it doesn't support search and filtering of the content in admin. So Admin can enhance the features of admin page and can have more control features.

## Mocks
It's an initial demo of the work.
![screenshot from 2018-03-08 23-16-43](https://user-images.githubusercontent.com/22910156/37167212-4dcde3c2-2327-11e8-9048-244124e1159a.png)

### Update [Required]
- [x] [Search by title, content etc ]
- [x] [Fiter by date like today, last seven days, months and year etc ]
- [x] [list_display extend of post ]

## Definition of Done
- [x] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[10] hours

**Comment by AnkurBegining** [comment]
@sa7i I would like to work on it. Please suggest your views.

**Comment by vigzmv** [comment]
@AnkurBegining the **Issue Description** should be 'As an Admin I should be able to Search....'

**Comment by AnkurBegining** [comment]
@vigzmv I accept my mistake of writing user instead of Admin. Would you please review my issue again and assign me this work. I would like to develop this functionality.

**Comment by vigzmv** [comment]
@ankurbegining It's still not right, the issues are written with User perspective. So like in my last comment it should be like  'As an Admin,  I should be able to Search and filter in the admin page...'

**Comment by AnkurBegining** [comment]
@vigzmv Now, please look at it and suggest your view.

**Comment by sakshi1499** [comment]
The issue wasn't approved, PR has been closed. Closing this issue.
