### ISSUE TITLE
Wiki Sidebar Update

### ISSUE THREAD

**Issue by mayburgos** [anitab-org/portal#368]
## Description
As a newcomer,
I need to navigate the repo successfully,
so that I can understand where the project is in its development.

## Mocks
![screen shot 2018-04-19 at 3 47 20 pm](https://user-images.githubusercontent.com/2440938/39014663-06dcb230-43e9-11e8-997c-96a89b7c55e8.png)

### Update [Required]
- [x] Update to [the template](https://docs.google.com/document/d/1h53P1h5g9hWEUsnOhpl9PgVzbWEGhTMIP2Pyta-MYSA/edit?usp=sharing) as discussed by the Community.
### Enhancement to Update [Optional]
- [x] Link all GSoC/Outreachy student's pages if applicable.
- [x] Link Final Reports page if applicable.

## Definition of Done
- [x] All of the required items are completed.
- [ ] Approval by 3 Community Members.

## Estimation
10-30 minutes

**Comment by Fenn-CS** [comment]
@MeepyMay please assign this to me.

**Comment by isabelcosta** [comment]
Updated here https://github.com/systers/portal/wiki
I used every page that existed in this wiki, they're all linkable from the sidebar
@systers/maintainers-portal 

![image](https://user-images.githubusercontent.com/11148726/70748301-ace47100-1d21-11ea-80f7-5e57c41a96c3.png)

**Comment by isabelcosta** [comment]
I am closing as this is done already @anitab-org/admins
