### ISSUE TITLE
Add the TODO section to the README.md

### ISSUE THREAD

**Issue by monajalal** [anitab-org/portal#371]
## Description
Please add the TODO section at the end of the portal README.md and once each task in TODO is done, please cross it (but don't remove it from the TODO list). For now, just add 3-4 TODOs either from the features suggested in the git issues that have highest importance or from the feature you would like to see in portal. This will help us not only to be organized and stay on track but also to show our users what are the feature that are not yet included but will be included in the future.

**Comment by Fenn-CS** [comment]
@monajalal  I am creating a TODO.md instead because the README.md has too much information already... This can be modified later if you have another idea on how we should do this when I send in the PR

**Comment by saurabhkanswal** [comment]
unassigned @Fenn-CS  as there is no response.

**Comment by sakshi1499** [comment]
Closing this issue as this is not relevant.
