### ISSUE TITLE
Systers logo is missing on Portal's GitHub Page

### ISSUE THREAD

**Issue by monajalal** [anitab-org/portal#373]
## Description
As a newcomer,
I need a proper Systers logo reference,
so that I can know which open source project falls under Systers.

### **Close Up**
![screenshot from 2018-05-04 21-29-40](https://user-images.githubusercontent.com/1892917/39658451-c49a3c66-4fe2-11e8-95ad-28f74aa379e4.png)

### **Full Screen**
![screenshot from 2018-05-04 21-30-17](https://user-images.githubusercontent.com/1892917/39658453-c89093b0-4fe2-11e8-8b40-8a245d83f9b3.png)

### Update [Required]
- [ ] Update the Systers logo to the [new branded logo](http://systers.io/images/systers-logo.png). 
- [ ] Fix the [broken png link](http://systers.org/systers-dev/lib/exe/fetch.php/systers-logo.png?w=300
) to properly reference an updated image.

### Enhancement to Update [Optional]
- [ ] Remove the old 2014 students, mentors, and project admins from the page. (A separate database is being created to properly assign contributors to the each repo's GitHub page.
- [ ] Look what has caused the logo to be missing and find a stable way (Amazon S3 storage?) to maintain images so they wouldn't fade away in the future. (Document first, then open a issue that helps solve this problem with the documentation attached.)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by monajalal** [comment]
Also logo is missing for Arab Women in Computing
![screenshot from 2018-05-04 22-04-16](https://user-images.githubusercontent.com/1892917/39658741-2f1ee8ee-4fe7-11e8-821d-788d8071a411.png)
In addition to Latina in Computing
![screenshot from 2018-05-04 22-05-04](https://user-images.githubusercontent.com/1892917/39658749-3fbedfb0-4fe7-11e8-9180-7afc339a202c.png)
Here
http://wiki.systers.org/open-source/doku.php/portal

**Comment by Oishika-Pradhan** [comment]
Is anyone already working on it? Or can I take up the task?

**Comment by Fenn-CS** [comment]
@Oishika-Pradhan It was assigned to me, but you can work on it as am working on a couple of other issues.

**Comment by Oishika-Pradhan** [comment]
Yes, I am taking up the issue @Fenn-CS

**Comment by MeepyMay** [comment]
@monajalal @Oishika-Pradhan @Fenn-CS There are 3 different issues here.

1. Move _old wiki data_ into an archived section in the Portal GitHub Wiki. (i.e. data from [here](http://wiki.systers.org/open-source/doku.php/portal) to our [GitHub Wiki here](https://github.com/systers/portal/wiki) **<<<** We're not using the Wiki anymore. It caused a lot of confusion to keep documentation in 3+ websites.
2. Logo update on the _Portal Web Application_: https://portal-dev.systers.org/ **>>>** Which can be included in a full "UI update" issue. Logo would be one of the checkboxes in a whole UI update.
3. Updating all of the documentation on Portal's _GitHub Website_: http://systers.io/portal **<<<** This needs a Systers OS update, we need a template to work on each of the projects' GitHub page. For example, [FirstAide Web](http://systers.io/FirstAide-web/) & [Portal](http://systers.io/portal) do not have a consistent branding or template.

The FirstAide Web and Portal applications are on a different website. Those GitHub Pages have been used for documentation in the past to help create setup instructions for the development environments.

**Comment by MeepyMay** [comment]
@Fenn-CS @monajalal @Oishika-Pradhan I updated the issue. Please create new issues that address the documentation migration and two UI updates (1. for the [Portal Web Application](https://portal.systers.org/) and 2. for a template to use across all GitHub web pages for each repo.)

Please label these low priority, category maintenance/enhancement (for UI), and status available for non-GSoC students to work on. Unless this is in your timelines @Fenn-CS @abhi20161997.

**Comment by Oishika-Pradhan** [comment]
@MeepyMay @monajalal then this issue is solved right? I have updated the logo (not referenced to some link, but added the logo in the `images` directory in the branch `gh-images`). The mentors and students list has only the first names though.
I'd also like to work on building a new uniform template for each repo.

**Comment by monajalal** [comment]
@Oishika-Pradhan you might be interested in working on https://github.com/systers/portal/issues/390

**Comment by rahulii** [comment]
Can i take up the task?

**Comment by abhi20161997** [comment]
@rahulii ya you can.

**Comment by rahulii** [comment]
Okay,Will take up tha task!

**Comment by rahulii** [comment]
All i have to do is fix the logo?Right?

**Comment by abhi20161997** [comment]
@rahulii Please refer to the comments before working on it

**Comment by manigedit** [comment]
As mentioned earlier, the logo is added to the img folder. If you want me to update the link instead of the static link, I expect this code to edit..
![screenshot from 2018-08-10 02-36-58](https://user-images.githubusercontent.com/37980499/43926204-25da5b5e-9c47-11e8-94bd-ec97577af1fb.png)

**Comment by manigedit** [comment]
Can I take up the task,if yes allot me.

**Comment by aganjali10** [comment]
Is the issue still open? Can you assign it to me?

**Comment by Fenn-CS** [comment]
Just proceed working on it. and send in a PR.

**Comment by jfflisikowski** [comment]
hello, I would gladly fix this, I'll just send a PR

**Comment by sakshi1499** [comment]
Closing this issue as it is not relevant anymore.
