### ISSUE TITLE
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

### ISSUE THREAD

**Issue by monajalal** [anitab-org/portal#378]
If you run step 5, without first running docker you will get the following error. Documents should change so that it reflect the fact that after installing docker you should run a command so that make sure it is running in the background:

```
[jalal@goku portal]$ docker-compose build
db uses an image, skipping
Building web
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

```

**Comment by mayburgos** [comment]
No one is currently using Docker to run Portal. We're going to update our documentation so we don't have Docker setup instructions.
