### ISSUE TITLE
Move old wiki data into an archived section in the Portal GitHub Wiki

### ISSUE THREAD

**Issue by Fenn-CS** [anitab-org/portal#380]
## Description
As a user, I need to be able to access all wiki data from one location.

### Update [Required]
- [ ] Move data from [wiki.systers.org](http://wiki.systers.org/open-source/doku.php/portal) to our [github wiki here](https://github.com/systers/portal/wiki)

## Definition of Done
- [ ] All of the required updates are completed.
- [ ] Approval by 2 mentors.

## Estimation
2 to 3 hours

**Comment by Oishika-Pradhan** [comment]
I can take this up.

**Comment by Fenn-CS** [comment]
@Oishika-Pradhan ok go ahead

**Comment by sakshi1499** [comment]
Closing this because old wiki data has been moved to the current one.
