### ISSUE TITLE
Create standard template to use all systers github pages

### ISSUE THREAD

**Issue by Fenn-CS** [anitab-org/portal#381]
## Description
As a visitor, developer etc I  need a template to see a consistent design on each of the projects github page. For example, FirstAide Web & Portal should have a consistent branding or template.

### Update [Required]
- [ ] A repeatable and simple template created

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours

**Comment by Oishika-Pradhan** [comment]
I'll be working on this.

**Comment by Fenn-CS** [comment]
@Oishika-Pradhan go ahead!

**Comment by SubbulakshmiRS** [comment]
Is work still being done ? If no, Can I be assigned to this issue ?

**Comment by sakshi1499** [comment]
The Design team is working on this. A new issue for the same has been created.
