### ISSUE TITLE
 Write automation scripts for dev-enviroment set up

### ISSUE THREAD

**Issue by Fenn-CS** [anitab-org/portal#384]
## Description
As a (new) developer I should be able to set up the development environment by running  a single (bash) script.
It would also be great to run a command afterward that does sanity checks and tells the above bash script has been ran successfully and environmental variables are set as well as the dev env.

## Mocks
[TO BE ADDED]

## Acceptance Criteria
- [ ] Write a bash script to automate the task
- [ ] Update documentation to cover new configuration method

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
2 hours

**Comment by Vishnupriya1507** [comment]
HI, can i take up this issue

**Comment by Fenn-CS** [comment]
Hello @Vishnupriya1507  this issue has been completed... I don't know what is delaying its merge.

**Comment by sakshi1499** [comment]
We are planning to incorporate this through Gitpod now. Will create a new issue for this. Closing this one.
