### ISSUE TITLE
Portal Communities should include the list of all communities in drop down menu

### ISSUE THREAD

**Issue by monajalal** [anitab-org/portal#390]
## Description
As a portal user, I need to be able to see an entire list of communities in the drop down menu for easier access. Right now it only shows three communities while the list is much longer.

## Mocks
[
![screenshot from 2018-05-16 19-20-12](https://user-images.githubusercontent.com/1892917/40148888-5e92f4e8-593e-11e8-9456-38ec1d6e4894.png)
]

### Update [Required]
- [ ] [Find the comprehensive list of Systers communities]
- [ ] [Add each item in the list in the drop down menu]
- [ ] [Make sure when you click on each item in the drop down menu it actually works and goes to that community dedicated Webpage]
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
[INSERT NUMBER HERE] 2 hours max

**Comment by lsurasani** [comment]
Hey! New to open source, looking for some easier/beginner friendly issues to tackle -- may I take this one?

**Comment by monajalal** [comment]
@lsurasani yeah this should be a good one. Go for it and please let us know how it goes. Once you are done please ping me for PR.

**Comment by monajalal** [comment]
list of all communities is available from here https://anitab.org/systers/systers-communities/

**Comment by SaravananOffl** [comment]
Hi, Can I work on this issue?

**Comment by devshiva619** [comment]
@monajalal Hey I am a newbie and would like to work on this

**Comment by anshulahuja98** [comment]
Hey can i work on this issue?

**Comment by Vishnupriya1507** [comment]
Hi, can i take up this issue.

**Comment by Phoenix0009** [comment]
Id like to take this issue.

**Comment by Mallik813** [comment]
Can I work on this issue if it is still open?

**Comment by BeKingsman** [comment]
@mayburgos  is this issue still available ? can i work on this ?

**Comment by sakshi1499** [comment]
Closing this as we have removed communities' list display now.
