### ISSUE TITLE
Configure travis.yml to permit staging enviroment run selenium tests

### ISSUE THREAD

**Issue by Fenn-CS** [anitab-org/portal#395]
## Description
All tests have to be run in the staging environment currently selenium test cannot be run, hence the skip flag is used on selenium tests.... _Devs may remove to flags to run test locally_

## Acceptance Criteria
- [x] Update travis.yml to permit selenium tests run
- [x]  Install required tools (Webdrivers)

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 2 mentors

## Estimation
4 hours

**Comment by sakshi1499** [comment]
PR for this issue has already been merged.
