### ISSUE TITLE
Change the link in the readme 

### ISSUE THREAD

**Issue by poojithansl** [anitab-org/portal#399]
## Description
In the readme, the link to clone portal is incorrect, as seen in issue #377 
## Acceptance Criteria
Convert `git clone git@github.com:systers/portal.git` 
into
 `git clone https://github.com/systers/portal.git` in the Readme.md for Docker, Windows and Linux installation steps.
### Update
- [ ] Update the Readme with the correct command.
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.
## Estimation
1/2 hour

**Comment by devshiva619** [comment]
@sa7i Hey I would like to work on this issue 😃

**Comment by sara-02** [comment]
@devshiva619 @sa7i This is not a valid issue IHMO.

**Comment by sara-02** [comment]
You can clone the repo either way. It should work.

**Comment by sara-02** [comment]
Ways to resolve it
1. Change the link in the readme.
To test the solution
2. Create a docker container using the updated readme.

**Comment by devshiva619** [comment]
@sara-02 so I can start working this. But I dont have any experience with docker. 😥

**Comment by sara-02** [comment]
@devshiva619 That is ok. You just have to follow the commands, no experience with docker is needed to solve this issue.

**Comment by devshiva619** [comment]
@sara-02 I ran this command `docker-compose run web python systers_portal/manage.py migrate` and I am geeting this error 
```
Traceback (most recent call last):
  File "systers_portal/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/src/portal/systers_portal/systers_portal/settings/docker.py", line 1, in <module>
    from .base import *
  File "/usr/src/portal/systers_portal/systers_portal/settings/base.py", line 20, in <module>
    SECRET_KEY = os.environ['SECRET_KEY']
  File "/usr/local/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'SECRET_KEY'
```

**Comment by sara-02** [comment]
@devshiva619 Point 9 in the readme should help. Please go through it once.
```
Run export SECRET_KEY=foobarbaz in your terminal, ideally the secret key should be 40 characters long, unique and unpredictable. Optionally to set the shell variable every time you activate the virtualenv, edit venv/bin/activate and add to the bottom the export statement.
```

**Comment by sara-02** [comment]
You can also create a .env file and add `SECRET_KEY=foobar` and then run `source .env`.
But make sure to never push your .env. So better to add it to `.gitignore`.
That way you won't have to run the export command everytime you run docker-compose from a new terminal.

**Comment by devshiva619** [comment]
@sara-02 Hey I am not yet assigned to this issue, so should I wait for it or I can make a PR directly?

**Comment by devshiva619** [comment]
@sara-02 I tried made a file named .env and then re-executed the command but same error 😥

**Comment by sara-02** [comment]
@sa7i @monajalal Can one of you assign the issue to @devshiva619

**Comment by sara-02** [comment]
> @sara-02 I tried made a file named .env and then re-executed the command but same error 
Are you still facing the issue?

**Comment by devshiva619** [comment]
@sa7i I did that but no luck

**Comment by sara-02** [comment]
@devshiva619 Can you perform this command `sudo useradd -U -s /bin/bash postgres` and then start with STEP 7 again. 
It is a known issue, while installing postgres it may not add default postgres users to your OS's user account. Thus, the unkown user error when using sudo.

**Comment by monajalal** [comment]
It doesn't allow me to assign it
![screenshot from 2018-05-23 15-49-01](https://user-images.githubusercontent.com/1892917/40447540-e9aa3f52-5ea0-11e8-8df7-ae50e2aefa30.png)
also tried without @ and the same!

**Comment by sara-02** [comment]
@monajalal no issues.

**Comment by aganjali10** [comment]
@sa7i I would like to work on this issue. Can you assign it to me?

**Comment by divya7shahi** [comment]
may I work on this issues,if nobody is working on it

**Comment by sara-02** [comment]
@divya7shahi We already have one PR pertaining to this issue, waiting to be merged.

**Comment by SunitiJain** [comment]
is this issue still open ?? can i work on it?
