### ISSUE TITLE
Location dropdown freezing browser on add meetup page

### ISSUE THREAD

**Issue by Fenn-CS** [anitab-org/portal#400]
## Description
As a user location dropdown should not freeze my browser when clicked. The expected behavior  (opening drop) should not misalign with the actual behavior (freezing browser)

## Enviroment
OS Spec : Ubuntu 16.04, 64bit 
Firefox 60.0.1
Chrome Version 66.0.3359.170

## Mocks

![add-meetup-location-dropdown](https://user-images.githubusercontent.com/14317775/40284770-d8b6e89c-5c8b-11e8-9e52-eb282f4aeebb.png)

## Acceptance Criteria
- [x] dropdown should work as expected

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 2 mentor.

## Estimation
2 hours

**Comment by sakshi1499** [comment]
This issue has been resolved.
