### ISSUE TITLE
Clicking on Asian Women in Computing dropdown menu in communities tab gives error

### ISSUE THREAD

**Issue by monajalal** [anitab-org/portal#409]
## Description
As a user,
I need to be able to click on any of the dropdown items in the communities menu,
so that I can access their content. For now clicking on Asian Women in Computing gives error. And the other pages don't have full content.

## Mocks
When I click on the communities in the communities dropdown, I get the error shown in the screenshot.

![screenshot from 2018-05-30 14-17-06](https://user-images.githubusercontent.com/1892917/40739482-5a3a2cdc-6414-11e8-8647-dfcee0de38e6.png)
![screenshot from 2018-05-30 14-16-49](https://user-images.githubusercontent.com/1892917/40739495-5e5241ec-6414-11e8-81fa-e679b56ec49a.png)

### Update [Required]
- [ ] [After clicking on each of the dropdown items in the menu guide me to the correct page]
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
[INSERT NUMBER HERE] 3 hours.

**Comment by arunikayadav42** [comment]
Is anybody still working on this?

**Comment by BeKingsman** [comment]
Hii @mayburgos , i would love to work on this issue. Can i proceed ?

**Comment by saurabhkanswal** [comment]
@BeKingsman are you still available to work on this issue.
thanks.

**Comment by sakshi1499** [comment]
We have completely removed this and changed the communities' drop down.
