### ISSUE TITLE
The link of the site http://portal.systers.org/ is not working

### ISSUE THREAD

**Issue by sarnava1** [anitab-org/portal#457]
## Description
As a USER,
I need to visit the portal website,
so that I can see what the features are so that I can contribute.

The link http://portal.systers.org/ is not working.

**Comment by abhishekspeer** [comment]
@sarnava1 I think it’s not working for now because the portal is being shifted and it’ll work as soon as shifting gets over.

**Comment by sammy1997** [comment]
@mayburgos @abhi20161997 The link still seems broken. Has the domain been configured properly?

**Comment by sakshi1499** [comment]
Closing this issue as a new domain name is being worked on and the link will be moved.
