### ISSUE TITLE
Remove design glitches at different screen sizes

### ISSUE THREAD

**Issue by abhishekspeer** [anitab-org/portal#458]
## Description
As a developer,
I need to ensure that the portal has a layout free of glitches at all screen sizes while retaining the basic design of portal at the same time. This will accomplish a responsive design for every screen size and an experience tailored to handheld devices as well.

## Mocks
![screenshot from 2018-12-22 19-49-29](https://user-images.githubusercontent.com/33948877/50377769-516d2f00-0649-11e9-9e8b-af65cd50bd0f.png)
![screenshot from 2018-12-22 19-50-12](https://user-images.githubusercontent.com/33948877/50377770-5205c580-0649-11e9-8ca7-c94daca5c938.png)
![screenshot from 2018-12-22 19-50-23](https://user-images.githubusercontent.com/33948877/50377771-5205c580-0649-11e9-86de-99f446a1a803.png)

### Update [Required]
- [x] CONTACT not shifting below from the lower navigation bar. 
- [x] SIGN UP and LOGIN does not overlap Systers Logo on reducing screen width.
- [x] Orientation of SIGN UP and LOGIN is fixed at reduced screen width. 

### Enhancement to Update [Optional]
- [x] Fix the signup and login button orientation on devices with smaller screen size.
- [x] Minimize the horizontal scrolling on handheld devices to offer a better user experience.

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
2 hours

**Comment by abhishekspeer** [comment]
@abhi20161997 
I have created an issue, please have a look and and assign it to me so that I can start working on it.

**Comment by abhi20161997** [comment]
@abhishekspeer You can start working on this issue.

**Comment by abhishekspeer** [comment]
@abhi20161997 Could you please review the changes and merge this patch if no changes are needed? Thanks!
