### ISSUE TITLE
Messages overlapping with Headings/Text

### ISSUE THREAD

**Issue by abhishekspeer** [anitab-org/portal#460]
## Description
As a Developer,
I need make some changes in the styling of the portal
so that the messages being displayed above the heading/text are easily readable.

## Mocks
![overwriting issue](https://user-images.githubusercontent.com/33948877/53317109-689df680-38f0-11e9-9510-bebaab96e172.png)
![overwriting_issue2](https://user-images.githubusercontent.com/33948877/53317114-6b98e700-38f0-11e9-8f46-77ba4b81e1ae.png)

### Update [Required]
- [x] Required changes in styling are made to ensure no overlapping.
### Enhancement to Update [Optional]
- [x] The messages are centre aligned so as to improve the overall feel. 

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.5 Hours

**Comment by ritwickraj78** [comment]
@abhishekspeer Could I please take up this issue?

**Comment by ritwickraj78** [comment]
Is this issue still open? Can I take this up?

**Comment by abhishekspeer** [comment]
Hi @ritwickraj78! Sorry, but this issue has been solved already and a PR is also referenced for the same. You can have a look at the submitted patch and suggest improvements if you find any or you can also look up for some other issue to work on. Hope it helps, Thanks!

**Comment by abhishekspeer** [comment]
@abhi20161997 could you please review it and merge it if it works? Thanks!
