### ISSUE TITLE
Update Django Crispy Forms

### ISSUE THREAD

**Issue by aayush-05** [anitab-org/portal#470]
## Description
It is always wise to use the updated packages as they contains a lot of bug fixes. Therefore I would suggest updating the django-crispy-forms package to 1.8.1 and alongwith make the requiredchange in the settings to use Bootstrap 4 (crispy-forms moved to bootstrap4 from 1.7.1 onwards).

### Update [Required]
- [ ] Update the required packages

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by anchalg00** [comment]
Hi @aayush-05 , I would like to work on this issue , i would love if you could assign it to me

**Comment by sammy1997** [comment]
Seems valid. But I think we should do all the package updates together than one by one. @abhi20161997 any views on that?

**Comment by sakshi1499** [comment]
@sammy1997 I second you on that.

**Comment by sakshi1499** [comment]
Django Crispy Forms were updated in a PR. So closing this issue now.
