### ISSUE TITLE
Outdated database settings

### ISSUE THREAD

**Issue by aayush-05** [anitab-org/portal#471]
## Description
The postgres database settings are a bit outdated with respect to the current Django version 1.11. Fix them to work fine with the current django version

### Update [Required]
- [ ] Change the settings as required

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by bismitaguha** [comment]
Hey @aayush-05 , I would like to work on this issue. Please could you assign it to me.

**Comment by aayush-05** [comment]
I am not a maintainer for this project, try asking on zulip

**Comment by sammy1997** [comment]
@aayush-05 What kind of changes do you want to be implemented? Can you explain a bit?

**Comment by aayush-05** [comment]
It is just a small syntax bug @sammy1997 . With django 1.11, we are not required to mention the database driver in the settings file. It is not a problem right now, but can be deprecated with the coming versions.
![image](https://user-images.githubusercontent.com/47032027/77146353-dfd09a80-6ab0-11ea-85e9-11741cb1ab64.png)

**Comment by ritwickraj78** [comment]
@sammy1997 @abhi20161997 I would like to take up this issue. May I start working on it?

**Comment by abhi20161997** [comment]
@ritwickraj78 Ya you can work on this !
