### ISSUE TITLE
Oauth service not working on current deployment

### ISSUE THREAD

**Issue by aayush-05** [anitab-org/portal#472]
## Description
Login/Signup via third party apps including Google, Twitter, GitHub, Facebook isn't working on the current deployment and returns the given error.

## Mocks
![image](https://user-images.githubusercontent.com/47032027/74167172-da7c6680-4c4d-11ea-934c-35d810280886.png)

### Update [Required]
- [ ] Fix the Oauth app/service to enable third party login

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 hours

**Comment by bismitaguha** [comment]
I am working on this issue

**Comment by anchalg00** [comment]
Hi , I would like to work on this issue , Please assign it to me

**Comment by BeKingsman** [comment]
Hii @isabelcosta , I would love to work on this issue. Can i proceed ?

**Comment by sammy1997** [comment]
@aayush-05 I think the URL has to be added to the Google developers console. How do you propose to resolve this? @abhi20161997 who has access to that currently?

**Comment by aayush-05** [comment]
@sammy1997 I am not sure but looks like this hasn't been developed on the backend yet. I couldn't find any authentication backends for these services in the settings file.

**Comment by satya7289** [comment]
@aayush-05 @sammy1997 Actually the credentials like CLIENT ID, SECRET KEY, KEY are not provided in the backend(Admin: Social Accounts › Social applications) for the social app provider. After adding these credentials it is working, I have checked for Facebook it is working on my localhost.

**Comment by aayush-05** [comment]
Ah, then maybe they aren't exposed for the development environment. But maybe we can have a dummy set added to the settings file, so any newcomer knows where to add them up. (maybe a section in readme help)

**Comment by satya7289** [comment]
I want to take up the issue.

**Comment by ritwickraj78** [comment]
@sakshi1499  I guess you must close this issue

**Comment by sakshi1499** [comment]
@ritwickraj78 Great! Thank You! 
Closing this issue. Now working on #533 during GSoC
