### ISSUE TITLE
confirmation email not received.

### ISSUE THREAD

**Issue by ninjakx** [anitab-org/portal#476]
## Description
When a user signs up a confirmation mail is sent but have not received it. More over the msg is getting overlaid by heading.

## Mocks
![Screenshot from 2020-02-25 00-23-18](https://user-images.githubusercontent.com/29797787/75181803-0bd45680-5765-11ea-9133-c3568d05ed00.png)

### Update [Required]
- [ ] [Fixing the UI]
- [ ] [Fixing the backend for mailing and verification]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by abhishekspeer** [comment]
Hi @ninjakx! This overlapping issue has already been  reported and solved which is referenced via a separate pull request already. Regarding the conformation Email, please go through the documentation once, you'll find that a confirmation mail is not actually triggered but the contents are printed in the terminal itself. With that being said, I'm afraid to mention that this issue needs to be closed. You can find other issues to work on or report other issues if you find any. Thanks!
