### ISSUE TITLE
Responsiveness of homepage

### ISSUE THREAD

**Issue by anmolcool007** [anitab-org/portal#477]
## Description
The homepage is not responsive, there is a horizontal overflow scroll.
Need to make the site responsive by changing HTML, CSS, and javascript

## Mocks
![Responsive](https://user-images.githubusercontent.com/43794036/75569381-f6b83a00-5a7a-11ea-8a81-fb07060e4dbc.png)

### Update [Required]
- [ ] Fix responsiveness

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[3] hours

**Comment by anmolcool007** [comment]
Found this issue with the responsiveness of the website.

Can I take this up??

**Comment by abhishekspeer** [comment]
Hi @anmolcool007, Sorry to say but this issue has already been reported, solved and referenced via a pull request which is yet to be reviewed and merged. I'm afraid to mention that this issue needs to be closed. If you want you can go through the pull request and suggest changes if you find any or you can find other issues to work on. Also, feel free to report other issues if you find any. Thanks!

**Comment by anmolcool007** [comment]
Sure.
Thank you
