### ISSUE TITLE
Error while setting up portal

### ISSUE THREAD

**Issue by arunikayadav42** [anitab-org/portal#478]
I had an error with the version of psycopg version 2.6 

Fix: change the version to >= 2.7
![psycopg-2 6_error](https://user-images.githubusercontent.com/28708494/75605215-d33ad100-5b06-11ea-8961-1859e6e98df4.png)

**Comment by abhishekspeer** [comment]
Hi @arunikayadav42, I'm not sure why version 2.6 is being installed in your case. Psycopg2 is already at version 2.7 as specified in the requirements.

Please find the requirements here for your reference: 
https://github.com/anitab-org/portal/tree/develop/requirements

**Comment by mayburgos** [comment]
@arunikayadav42 Abhishek has tried to help. Please respond.

Also, please use the issue templates we provide.

**Comment by arunikayadav42** [comment]
I am not sure why is it happening. Is there any work around?

**Comment by abhishekspeer** [comment]
No worries @arunikayadav42. I’d recommend  you to go through README once. You’ll find all the steps to be followed in order successfully setup the development/production environment there. While following those steps, let us know in case you’re stuck. Here’s the link:
https://github.com/anitab-org/portal/blob/develop/README.md

**Comment by arunikayadav42** [comment]
Thanks a lot for helping out. I have been able to run it locally :)
