### ISSUE TITLE
Bracket missing on the request community page

### ISSUE THREAD

**Issue by ritwickraj78** [anitab-org/portal#479]
## Description
The request community form has a bracket in the Types of Community option.

## Estimation
[0.2] hours 
![Screenshot from 2020-03-05 02-20-55](https://user-images.githubusercontent.com/43514828/75921891-f90a0200-5e87-11ea-997b-6231ef0f7d58.png)

**Comment by ritwickraj78** [comment]
@abhi20161997 The constants.py file in the community has a typo. I would like to fix it. Could you please assign this to me? Thank you

**Comment by abhi20161997** [comment]
@ritwickraj78 Ya thanks for detecting this minor yet critical bug. Please go on to work on this.

**Comment by sammy1997** [comment]
@ritwickraj78 I see you were assigned this issue. Please send a PR or let us know if you are working on a different issue

**Comment by ritwickraj78** [comment]
@sammy1997 if you could please review and merge my PR #506 . I will submit a PR for this issue as well.

**Comment by ritwickraj78** [comment]
@sammy1997 I have linked a PR which fixes #453 and #479
