### ISSUE TITLE
Add section on README to redirect contributors to Zulip channel regarding portal

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/portal#482]
## Description

As a contributor,
I need to know where I can reach out the community,
so that I can discuss or see discussions of this project.

I would suggest adding a section such as "Contact us" or "How to reach us" to the README.
An example is what is on [mentorship-backend README](https://github.com/anitab-org/mentorship-backend/).

### Update [Required]
- [ ] Add contact section with AnitaB.org Open Source Zulip link and #portal stream link. 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by arunikayadav42** [comment]
Hi @isabelcosta can I work on this issue please?

**Comment by sayashraaj** [comment]
Hey, I have updated the Readme.md file according to #482 description of issue.
I have opened a PR with all the necessary changes completed
Thank You

**Comment by sayashraaj** [comment]
Can I be assigned to work on this issue? I had opened a PR without being assigned by mistake. But I have done the work as requested in the issue #482

**Comment by arunikayadav42** [comment]
@isabelcosta I asked before to work on the issue. I could have also opened a pull request but awaited for you to assign the issue to me. Please assign the issue to me so that I can rightfully work on it. Thanks

**Comment by arunikayadav42** [comment]
@sammy1997 please assign this issue to me. Thanks.

**Comment by isabelcosta** [comment]
@arunikayadav42 I will assign this to you :)

**Comment by isabelcosta** [comment]
@arunikayadav42 do you need any help with this issue? Do you have any updates?

**Comment by arunikayadav42** [comment]
Yeah! I had some issues with my PC. will create a pull request.
