### ISSUE TITLE
Verify Email-Address message not displayed properly

### ISSUE THREAD

**Issue by arunikayadav42** [anitab-org/portal#486]
## Description
As a user,
I should be able to to see the verify email address  properly but it appears as shown in the mock below
#
## Mocks
![Screenshot from 2020-03-09 17-50-21](https://user-images.githubusercontent.com/28708494/76212489-97061f80-622e-11ea-8f37-eeb4c96a1fd7.png)

### Update [Required]
- [ ] [Add support for such functionality]
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[1] hours

**Comment by abhishekspeer** [comment]
Hi @arunikayadav42 , Sorry to say but this issue has already been reported, solved and referenced via a pull request which is yet to be reviewed and merged. I'm afraid to mention that this issue needs to be closed. If you want you can go through the pull request and suggest changes if you find any or you can find other issues to work on. Also, feel free to report other issues if you find any. Thanks!
