### ISSUE TITLE
Fix Travis CI build which is failing for psql dependency

### ISSUE THREAD

**Issue by sammy1997** [anitab-org/portal#487]
## Description
As a developer,
I need update the travis yml file,
so that the PR builds fail.

## Mocks
![PSQL Error](https://user-images.githubusercontent.com/24635701/76324808-89bf6280-630c-11ea-88fd-9f925fcdcc56.png)

### Update [Required]
- [ ] Travis should not fail for postgres or other setup errors

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[INSERT NUMBER HERE] hours

**Comment by ritwickraj78** [comment]
@sammy1997 I would like to give it a try

**Comment by sammy1997** [comment]
@ritwickraj78 Go ahead. Please do this on a priority!

**Comment by ritwickraj78** [comment]
Yaa sure

**Comment by ritwickraj78** [comment]
@sammy1997 While squashing commits I made a few errors so I have opened a new pull request all over again. The test which I have changed was causing an assertion error. The values posted did not match so had to make this change. Thank you and sorry for the inconvenience.
