### ISSUE TITLE
Add in readme file that empty password not allowed in database settings

### ISSUE THREAD

**Issue by arunikayadav42** [anitab-org/portal#491]
## Description
As a contributor,
I should be able to setup the local database with an empty password too,
but there are errors when so done. We can add in the readme file that such password must not be empty.

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [ ] Add this warning in the readme file

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by bismitaguha** [comment]
Hey @arunikayadav42 , I am working on this issue.

**Comment by arunikayadav42** [comment]
Hi I am a contributor too :). I am waiting for some maintained to add the necessary labels to it so that I can start working on it. Thanks

**Comment by arunikayadav42** [comment]
@sammy1997 @isabelcosta please add the necessary labels to it . thanks

**Comment by sammy1997** [comment]
Hi @bismitaguha ! Please don't send PRs without getting assigned or without the issue getting approved!

**Comment by bismitaguha** [comment]
@sammy1997 Will surely follow the rules!

**Comment by sammy1997** [comment]
Approving this issue. But as it is a minor change in the documentation and no one has been assigned yet, I am keeping this as a first-timer issue

**Comment by BeKingsman** [comment]
can i take this issue ?

**Comment by arunikayadav42** [comment]
@sammy1997 can I take up this issue next?

**Comment by arunikayadav42** [comment]
@sammy1997 @isabelcosta @abhi20161997 can I take this issue up?

**Comment by abhi20161997** [comment]
@arunikayadav42 ya please go on to work on this.

**Comment by sammy1997** [comment]
@arunikayadav42 Status on this?
