### ISSUE TITLE
Update references on CONTRIBUTING.md from slack to zulip

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/portal#494]
## Description

As a contributor,
I need updated references to communication channels used by the community,
so that I can reach out to the community in the correct channels.

Contributing guidelines has still a reference to Slack channels. It should have link to Zulip and the appropriate stream. This should minimize confusion from newcomers

### Update [Required]
- [ ] Update CONTRIBUTING.md to have links to Zulip space and stream instead of Slack channel.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation

30 min

**Comment by bismitaguha** [comment]
@isabelcosta Please could you assign this issue to me.
