### ISSUE TITLE
Remove broken links from README

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/portal#495]
## Description

As a contributor,
I need up to date information on README,
so that I can understand the current state of the project.

Some links on README are out of date. Some of these are links at the beginning of the wiki that lead nowhere.

### Update [Required]
- [ ] Update/Remove broken links on README

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
30 min

**Comment by bismitaguha** [comment]
@isabelcosta I would like to work on this issue. I have checked the working and not working links for the purpose.

**Comment by isabelcosta** [comment]
@bismitaguha I see you already are working on a first timers only issue, because of that can you please look for other issues? Feel free to share your findings here, if you want.

**Comment by BeKingsman** [comment]
@isabelcosta  Can i work on this issue ?

**Comment by rsharvill** [comment]
@isabelcosta I would be happy to work on this issue if still available!

**Comment by anchalg00** [comment]
@isabelcosta Please can you assign this issue to me

**Comment by sammy1997** [comment]
@BeKingsman As your's is the first comment, I am assigning this to you!

**Comment by BeKingsman** [comment]
@sammy1997  Working on it.
