### ISSUE TITLE
Add .vscode/ to .gitignore

### ISSUE THREAD

**Issue by bismitaguha** [anitab-org/portal#497]
## Description
As a developer,
I need usually push updated code, and `.vscode/` is not added in the `.gitignore`. All the users using VSCode IDE for contributing are facing the same issue.

## Mocks
N/A

### Update [Required]
- [x] `.gitignore` file

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.25 hours

**Comment by bismitaguha** [comment]
@isabelcosta I would like to work on this issue.

**Comment by annabauza** [comment]
makes sense! approved.
