### ISSUE TITLE
Update test_post_view for Travis CI build to pass

### ISSUE THREAD

**Issue by sammy1997** [anitab-org/portal#502]
## Description
As a developer,
I need to update a test,
so that the Travis build passes.

## Mocks

![Screenshot from 2020-03-16 14-29-59](https://user-images.githubusercontent.com/24635701/76739837-d1257300-6792-11ea-88ea-ea83a4836b7f.png)

### Update [Required]
- [ ] Travis build should pass

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by sammy1997** [comment]
@ritwickraj78 You can work on this as discussed!

**Comment by ritwickraj78** [comment]
Yes working on it!

**Comment by ritwickraj78** [comment]
@sammy1997  Shall I make the required changes in .gitignore file as well as mentioned in issue #497 ?
