### ISSUE TITLE
Project link broken 

### ISSUE THREAD

**Issue by kashishmadan** [anitab-org/portal#509]
## Description
As a [USER],
I need [TO DO THIS],
so that I can [ACCOMPLISH THAT].

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [ ] [LIST ITEMS]
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[INSERT NUMBER HERE] hours

**Comment by kashishmadan** [comment]
For the root URL, the index.html is not provided

**Comment by sammy1997** [comment]
Please follow issue template
