### ISSUE TITLE
Change "Sign up" to "Sign in"

### ISSUE THREAD

**Issue by BeKingsman** [anitab-org/portal#510]
## Description
As a user, i need to see "Sign in using ...." instead of "Sign up using ..." at the login page.

# Mocks
<img width="1440" alt="login page" src="https://user-images.githubusercontent.com/53928332/77140933-2a4a1b00-6aa1-11ea-8a8b-e82fd4b24012.png">

### Update [Required]
- Code has to be updated

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.2 hours

**Comment by BeKingsman** [comment]
@sammy1997 Can fix this issue now ?

**Comment by sammy1997** [comment]
Yeah go ahead

**Comment by BeKingsman** [comment]
@sammy1997 working on it. will link the PR soon. Thanks for assigning.
