### ISSUE TITLE
Updating "Setup for developers (Windows)" section of the README

### ISSUE THREAD

**Issue by anchalg00** [anitab-org/portal#511]
## Description
As a user,
I need to be able to build the application on windows as smoothly as I can on linux, but there are a few errors encountered even when the steps of the README are exactly followed .

The "Setup for developers (Windows)" section of the README needs to be updated so that these errors can be avoided.

## Mocks
The following error is encountered after running "python manage.py migrate" , i.e step 5.3 of the "Setup for developers (Windows)" section of the README
![Screenshot (12)](https://user-images.githubusercontent.com/53042471/77182508-520fa200-6ae6-11ea-8fb2-d05426c88cf4.png)

### Update [Required]
- [ ] Update "Setup for developers (Windows)" section of the README

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by sammy1997** [comment]
Hey @anchalg00 ! Approved the issue! Please comment if you want to work on it, or if I should open it up for others

**Comment by anchalg00** [comment]
@sammy1997 Please assign this issue to me , thank you !

**Comment by sammy1997** [comment]
Go ahead @anchalg00 !
