### ISSUE TITLE
Virtual Meetup on a Zoom/Hangouts/WebEx Call with a CTA

### ISSUE THREAD

**Issue by pratyushchry** [anitab-org/portal#516]
## Description
Users should also be allowed to organize virtual meetups using video conferencing applications like Zoom/Hangouts/WebEx calls. This is very vital now that most parts of the world are under lockdown and amidst COVID 19, we must follow and encourage social distancing. 

### Update [Required]
- [ ] Add option for members to RSVP themselves with a Zoom/Hangouts Call Link
- [ ] Also have a button informing others to set up a Zoom/Hangouts Call

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[INSERT NUMBER HERE] hours

**Comment by sakshi1499** [comment]
This is being done in GSoC'20. A new issue for this exists.
