### ISSUE TITLE
Mapview of Communities UI

### ISSUE THREAD

**Issue by sakshi1499** [anitab-org/portal#527]
## Description
As a User,
I should be able to look at the Mapview of communities and filter communities as per my region preference.
so that I can have a better understanding of the communities in and around me.

## Mocks
Have to be created to satisfy the above description.
The Mapview Community Page should include:
1) Search option (sticky search)
2) Community Grids
3) Map pinpointing the location selected.

***Possible Enhancement***
Option to select the region.

***Icebox***
Mock of the page when no nearby community is present. 

Inspiration can be taken from https://developers.google.com/community/dsc/clubs
[Branding Guidelines](https://anitab-org.zulipchat.com/#narrow/stream/216323-design/topic/Branding.20Guidelines) should be taken care of.
## Acceptance Criteria
The above features should be presented in the mock in a user friendly manner.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
6 hours max.

**Comment by ritwickraj78** [comment]
@mayburgos  @sammy1997  @sakshi1499 Here is the previous mockup.
![1 - Screen 1](https://user-images.githubusercontent.com/43514828/82785441-362ad280-9e80-11ea-9a4c-3ea39d76752a.png)

**Comment by ritwickraj78** [comment]
The updated UI
![1 - Screen 1](https://user-images.githubusercontent.com/43514828/82788256-bbfd4c80-9e85-11ea-9f60-2fc9b2b4c40c.png)

**Comment by sakshi1499** [comment]
@ritwickraj78 There are some alignment issues, but its better than before. @mayburgos Should the systers icon be discontinued (anna suggested so) ?

**Comment by ritwickraj78** [comment]
@sakshi1499 The alignment issues will be solved while making the actual views IG. Those alignment issues you see are just errors of the human hand :)

**Comment by SanketDG** [comment]
@ritwickraj78 

The UI mockups don't look ideal but I understand they are just mockups and the real thing will come out much differently. Here are a couple of pointers (on the real thing, not the mockup (: )

- Is that a mockup of a specific Map tool being used? Also, what Map tool have you decided to use when this will be implemented in the near future?
- When one hovers over a community, the card should have more information like `Location` and `Chapter Leaders`

---
In case you don't know, I am the new mentor for your project. I hope everything is okay in your city with the current situation. 

---

---

**Comment by mayburgos** [comment]
@SanketDG We already made these decisions as mentioned in the other issue, please open new UI issues for other community members to claim to address the UI changes you mentioned.

**Comment by ritwickraj78** [comment]
@SanketDG  Its google maps API. And also when one hovers the box contains a link which takes us directly to the community page which contains all the details.

**Comment by sakshi1499** [comment]
Closing UI issues, as the design team will make new issues in case required.
