### ISSUE TITLE
Margins on every page.

### ISSUE THREAD

**Issue by satya7289** [anitab-org/portal#530]
## Description
Margins of every page need to be fixed.

## Mocks
reference 
<img width="528" alt="Screenshot-2020-05-09-at-19 00 44" src="https://user-images.githubusercontent.com/35588980/82121457-cbf09e80-97aa-11ea-9d7b-ee860adeca44.png">

### Update [Required]
- [x] Margins of every page should be fixed.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
5 hours

**Comment by yashshah2820** [comment]
on it 👍
