### ISSUE TITLE
Meetup Search page UI revamp

### ISSUE THREAD

**Issue by sammy1997** [anitab-org/portal#541]
## Description
As a user,
I need a better meetup search interface, without the date field and with a distance similar to [Meetup.com](https://www.meetup.com) event search page.

## Mocks
![ss_search](https://user-images.githubusercontent.com/24635701/82236716-25470200-9952-11ea-9530-8b5dd142f2bc.png)

### Update [Required]
- [ ] Remove meetup location dropdown
- [ ] Remove date field. Sort results by date as a defaut
- [ ] Remove date filter, keep a distance filter
- [ ] Keep a current location or typed location based search

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor and an admin.

## Estimation
3-4 days

**Comment by sakshi1499** [comment]
Closing this issue as it has been worked on. New issue for the new UI will be created later.
