### ISSUE TITLE
Individual Meetup Page UI

### ISSUE THREAD

**Issue by sakshi1499** [anitab-org/portal#543]
## Description
As a user,
I need to have a simple meetup page for individual events,
so that I can RSVP/Subscribe to a particular event and see suggested events.

##Mocks
The UI should include:
1. Resources/ Gallery of the event.
2. RSVP option so that they can receive emails about any updates to a particular event.
3. Suggested Events related to the event they have RSVP'ed about.

## Acceptance Criteria
Should follow the [Branding Guidelines](https://anitab-org.zulipchat.com/#narrow/stream/216323-design/topic/Branding.20Guidelines)

Inspiration can be taken from [this page](https://www.meetup.com/TensorFlow-London/) & [this page](https://community.anitab.org/event/)

## Definition of Done
- [ ] All of the above required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
12 hours max.

**Comment by ritwickraj78** [comment]
@sakshi1499 The RSVP feature is already there in the Meetups Page. So i just need to add a suggested meetup section at the bottom right?

**Comment by sakshi1499** [comment]
Yes, but the mock you make will show the full page right? It was just mentioned so you don't miss what's important in that page. ☺️ @ritwickraj78

**Comment by ritwickraj78** [comment]
@sakshi1499  Alright!

**Comment by ritwickraj78** [comment]
This part would be at the end of the meetup page. @mayburgos @sakshi1499 @SanketDG @sammy1997 
![1 - Screen  4](https://user-images.githubusercontent.com/43514828/83361428-8df89a80-a3a6-11ea-875b-0170268537c6.png)

**Comment by sammy1997** [comment]
Looks good. Just left align the text than center aligning them. I think that would look better

**Comment by sakshi1499** [comment]
+1 @sammy1997

**Comment by ritwickraj78** [comment]
@sammy1997 Cool will keep the changes in mind while making it

**Comment by sakshi1499** [comment]
Closing this issue as it has been worked on. New UI issue will be created later.
