### ISSUE TITLE
UI Mocks for Subsciption Settings

### ISSUE THREAD

**Issue by sammy1997** [anitab-org/portal#544]
## Description
As a user,
I need to be able to see a settings page,
so that I can select the types of notifications that I should receive.

Following options should be there in the settings: 

1. Community Updates
a. Upcoming Events for Communities I’m a member of (eg:- weekly digest that includes the upcoming events for multiple communities)
b. Updates from Community Interactions(eg:- weekly digest that includes stat changes of the community)

2. Meetup Updates for RSVP’ed Meetups
a. Receive updates on Location Change
b. Receive updates on Date Change
c. Receive updates on Time Changed
d. Reminders for the event (1 day prior, 1 hour prior)

## Mocks
![ss3](https://user-images.githubusercontent.com/24635701/83049943-697c8580-a069-11ea-9bb2-6720fcd4a9ae.png)

### Update [Required]
- [ ] Create a UI mock with the above options as settings

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 days

**Comment by ritwickraj78** [comment]
@mayburgos  @sakshi1499 @sammy1997  @SanketDG Will this be fine for a rough mock?
![3 - Screen 3](https://user-images.githubusercontent.com/43514828/83360974-e168e980-a3a2-11ea-9743-4a477902ec54.png)

**Comment by sakshi1499** [comment]
@ritwickraj78 It looks great😍
I'll take in suggestions from design team and make issues for community 😬

**Comment by sammy1997** [comment]
Seems good @ritwickraj78 !

**Comment by sakshi1499** [comment]
Closing this issue as it has been worked on. New UI issue will be created later.
