### ISSUE TITLE
Remove google plus sharing button

### ISSUE THREAD

**Issue by saurabhkanswal** [anitab-org/portal#545]
As a user when i try to share any meetup event using google plus button, then it shows me that Google Plus is no longer available.
so there is no need of google plus sharing button now as google plus is no longer available.

## Mocks
![21](https://user-images.githubusercontent.com/26677033/83058224-a9e20080-a075-11ea-904e-6493585b3a05.PNG)

### Update [Required]
- [ ] remove google plus button
- [ ] post screenshot  

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by gaurivn** [comment]
@saurabhkanswal , I am a first timer to Portal, I would like to work on this issue if it gets approved.

**Comment by saurabhkanswal** [comment]
@gaurivn as i can see you are in manager team, not in coding team. i don't think you're eligible. please correct me if i am mistaken.😊
thanks

**Comment by husainattar** [comment]
@saurabhkanswal I would like to work on this issue.

**Comment by gaurivn** [comment]
> @gaurivn as i can see you are in manager team, not in coding team. i don't think you're eligible. please correct me if i am mistaken.blush
> thanks

I am not aware of any rules like only people from coding team can solve first timer issues. I am not sure actually but never heard of it. Since I am a first timer to portal, can't I work on this issue?

**Comment by saurabhkanswal** [comment]
> @saurabhkanswal I would like to work on this issue.

@husainattar sure, iam assigning you this issue.

**Comment by gaurivn** [comment]
> @gaurivn as i can see you are in manager team, not in coding team. i don't think you're eligible. please correct me if i am mistaken.blush
> thanks

Please do confirm this with @anitab-org/admins . I had asked in Zulip too and commented here first. Grateful if you could look into this.

**Comment by saurabhkanswal** [comment]
@gaurivn  no, you are not eligible for coding issues. you can check [here](https://github.com/orgs/anitab-org/teams?query=%40gaurivn) for teams you are in.

**Comment by gaurivn** [comment]
> @gaurivn no, you are not eligible for coding issues. you can check [here](https://github.com/orgs/anitab-org/teams?query=%40gaurivn) for teams you are in.

I am eligible since I am a first timer and commented first on this first timer issue.

**Comment by gaurivn** [comment]
I am indeed eligible as a first timer.

**Comment by saurabhkanswal** [comment]
@husainattar any update?

**Comment by husainattar** [comment]
@saurabhkanswal  yes I have completed it on the same day but there was some error I don't while creating meetup I was not able to select a location that's why I was not able to take screenshots. I guess it was some other issues. BTW my code passed the test.

**Comment by husainattar** [comment]
@saurabhkanswal  I am going to create a pull request.

**Comment by saurabhkanswal** [comment]
@husainattar let me check
btw you can check the implementation of the share button here #274

**Comment by Tanuj22** [comment]
@saurabhkanswal Is this issue taken/assigned? I would like to work on it

**Comment by husainattar** [comment]
Hi @Tanuj22 actually I have been assigned working on this issue and I am going to create a merge request

**Comment by saurabhkanswal** [comment]
@husainattar i will create another issue for location error, you can create PR. 🎊 
thanks
