### ISSUE TITLE
Community updates on joining

### ISSUE THREAD

**Issue by sammy1997** [anitab-org/portal#550]
## Description
As a user,
I should receive weekly updates about a community once I join it,
and this should be according to the selected settings as mentioned in #549.

## Mocks
No UI mocks needed

### Update [Required]
- [ ] Create a view to handle community updates for members
- [ ] Write the tests for the views

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 days

**Comment by sakshi1499** [comment]
This issue was merged in a PR by Ritwick. Closing this.
