### ISSUE TITLE
Upgrade Django to latest version

### ISSUE THREAD

**Issue by satya7289** [anitab-org/portal#565]
## Description
As a developer,
I need upgrade Django.
so that portal is up to date with the latest dependency.

## Acceptance Criteria
Django is updated to latest stable version.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
4 hours

**Comment by satya7289** [comment]
If this is approved, I want to work on this.

**Comment by sakshi1499** [comment]
@satya7289 Add the version to which we are moving. This issue is now available. Sanket also wants to work on it. So in case you have any doubts reach out to me or @SanketDG

**Comment by sakshi1499** [comment]
@satya7289 Please confirm once if you still want to work on it, I'll assign accordingly.

**Comment by satya7289** [comment]
Yes, interested. Django version 2 @sakshi1499

**Comment by sakshi1499** [comment]
@satya7289 Isn't the latest version 3.0.8?

**Comment by SanketDG** [comment]
2.2 is LTS, but let's just go with 3.0, we can be bleeding edge :rocket:
